module.exports = {
  runtimeConfig: true,
  jsxRuntime: 'automatic',
  icon: true,
  typescript: true,
  dimensions: false,
  expandProps: false,
  prettier: true,
  prettierConfig: '.prettierrc.cjs',
  svgo: false,
  // svgoConfig: '.svgorc.cjs',
  ref: false,
  memo: false,
  replaceAttrValues: {
    '#91BEFF': 'var(--icon-main)',
    '#1F78F0': 'var(--icon-accent)',
  },
  titleProp: false,
  outDir: 'src/components/icons',
  index: true,
  ignoreExisting: false,
  filenameCase: 'pascal',
  ext: 'tsx',
} 
